### ISSUE TITLE
Qt Modules missing, but they are installed

### ISSUE THREAD

**Issue by ACH1980** [emper0r/IVAO-status#9]
Every time I try to start this, I get this error:
`You have not installed the packages Qt Modules for Python,

please run command as root:  aptitude install python-qt4

with all dependencies.`

I have installed python-qt4 and still getting this error...

**Comment by emper0r** [comment]
Hi @ACH1980 , sorry for delay answer, this project was developer 8 yrs ago, I think it's very unstable today but if continue to try it. you can delete this lines in the main file to continue to test it.

```
try:
    """Check if PyQt4 is installed or not, this library is a dependency of all,
    if not installed read the README.rst"""
    from PyQt4.QtCore import *
    from PyQt4.QtGui import *
    from PyQt4.QtWebKit import *
    from PyQt4.Qt import *
except ImportError:
    print ('\nYou have not installed the packages Qt Modules for Python,\n')
    print ('please run command as root:  aptitude install python-qt4\n')
    print ('with all dependencies.\n\n')
    sys.exit(2)
```
I'll move this project into python3 and Qt5 to keep it more stable next time. When...!? don't know but it's on plan. :)

regards and thanks for test it.
